name = "jlcookie-license"
main = "worker.js"
compatibility_date = "2026-07-05"
workers_dev = true
preview_urls = false

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "jlcookie_license"
database_id = "7f2e3beb-e10b-4643-b4b5-d6ad0ea1dabd"

[vars]
APP_VERSION = "V2.0.1 Premium"
DOWNLOAD_URL = "https://github.com/JLKunakorn/JLBotCookie-Release/releases/download/v2.0.1/JLmain_V2.0.1_Premium.exe"
ZIP_URL = "https://github.com/JLKunakorn/JLBotCookie-Release/releases/download/v2.0.1/JLmain_V2.0.1_Premium.zip"
PROMAX_APP_VERSION = "V2.0.3 ProMax"
PROMAX_DOWNLOAD_URL = "https://github.com/JLKunakorn/JLBotCookie-Promax-Release/releases/download/v2.0.3/Beta.JLBotPromax_V2.0.3_ProMax.exe"
PROMAX_ZIP_URL = "https://github.com/JLKunakorn/JLBotCookie-Promax-Release/releases/download/v2.0.3/Beta.JLBotPromax_V2.0.3_ProMax.zip"
